file_host_app/files/models.py
from file_host_app import db

class FileBase(db.Model):
    """
    """
    __tablename__ = 'file_base'

    file_id = db.Column(db.Integer, primary_key = True, autoincrement=True)
    original_name = db.Column(db.String(64), nullable=False)	
    user_id  = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    permission_of_file = db.Column(db.Enum('private', 'link', 'pablic', name = 'permission_of_file'), default = 'privat')	
    file_path = db.Column(db.String(80), nullable=False)
    count_download = db.Column(db.Integer, default=0)
    link = db.relationship('UserLinks', backref='links_for_user', lazy='dynamic')
    

    def __repr__(self):
        return '<File %r>' % (self.original_name)


class UserLinks(db.Model):
    """
    """
    __tablename__ = 'user_links'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'),nullable=False)
    file_id = db.Column(db.Integer,db.ForeignKey('file_base.file_id'), nullable=False)

file_host_app/__init__.py
import os
import click
from flask.cli import with_appcontext

from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app(config):
    # create and configure the app
    app = Flask(__name__)

    # app.config.from_object(config)
    app.config['SECRET_KEY'] = 'key'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///' + os.path.join(os.path.dirname(__file__), 'app.db') 
    app.config['FLASK_ADMIN_SWATCH'] = '007'

    db.init_app(app)

    from file_host_app.auth import auth as auth_bp
    app.register_blueprint(auth_bp)

    from file_host_app.files import file_host as files_bp
    app.register_blueprint(files_bp)
    app.add_url_rule('/', endpoint='index')
    
    from file_host_app.auth import models, auth_view, auth_utils
    from file_host_app.files import models, file_view, files_utils

    return app

file_host_app/files/__init__.py
from flask import Blueprint

file_host = Blueprint('file_host', __name__)

from . import file_view, files_utils, models

file_host_app/views/auth_view.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash

from utils import utils_auth

bp = Blueprint('auth', __name__, url_prefix='/auth')

@bp.route('/register', methods=('GET', 'POST'))
def register():
    """ 
    user registration page 
    """

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        
        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'

        if error is None:
            try:
                utils_auth.create_user(username, password)
            except:
                error = f"User {username} is already registered."
            else:
                return redirect(url_for("auth.login"))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    """ 
    user authentication page 
    """ 
    
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        user = utils_auth.data_of_user(username, password)

        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user['password'], password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user['id']
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')

@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = utils_auth.load_user(user_id)

@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

file_host_app/views/file_view.py
from flask import (
    Blueprint, flash, g, redirect, render_template, request, url_for, send_from_directory
)

from file_host_app.auth import login_required
from ..config import UPLOAD_FOLDER
from utils import utils_file

bp = Blueprint('file_host', __name__)

@bp.route('/')
def index():
    """
    main page with a list of all public files 
    """
    
    files =  utils_file.data_of_pablic_files()  
    
    return render_template('file_host/index.html', files=files)


@bp.route('/upload', methods=('GET', 'POST'))
@login_required
def upload():
    """ 
    page with a file adding form 
    """

    if request.method == 'GET':
        return render_template('file_host/upload.html')  
    
    file = request.files['file']

    if file and utils_file.allowed_file(file.filename):
        original_name = file.filename
        permission_of_file = request.form['permission']	
        file_path = utils_file.get_name_uuid()
        file.save(UPLOAD_FOLDER+'/'+file_path)
        
        utils_file.upload_file(original_name, g.user['id'], permission_of_file, file_path)
        
        return redirect(url_for('file_host.index'))

    if not file:
        flash('File is required.')

@bp.route('/download/<path:file_id>', methods=['GET', 'POST'])
@login_required
def download(file_id):
    """ 
    file download  
    """
    
    file_id = file_id
    error = None
    
    file = utils_file.download_file(file_id)
    
    if file[3] == g.user['id']:
        utils_file.count_downloaded(file_id)
        
        return send_from_directory(UPLOAD_FOLDER, file[2], attachment_filename=file[0], as_attachment=True)

    if file[1] != 'private':
        existing_entry = utils_file.check_access_by_link(g.user['id'], file_id)

        if existing_entry is None:
            utils_file.create_access_by_link(g.user['id'], file_id)
        utils_file.count_downloaded(file_id)
        
        return send_from_directory(UPLOAD_FOLDER, file[2], attachment_filename=file[0], as_attachment=True)
    
    flash('No permission to download the file.')


@bp.route('/my_files')
@login_required
def my_files():
    """ 
    displays a list of files uploaded by the user 
    """
    files = utils_file.data_of_user_files()
    
    return render_template('file_host/my_files.html', files=files)


@bp.route('/my_links')
@login_required
def my_links():
    """
    displays a list of files the user has access to
    """

    files = utils_file.data_of_links_users(g.user['id'])
        
    return render_template('file_host/my_links.html', files=files)

file_host_app/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Welcom</title>
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<nav>
  <h1> 
    <a class="action" href="{{ url_for('file_host.index') }}">Files</a>
  </h1>
  <ul>
    {% if g.user %}
      <li><span>{{ g.user['username'] }}</span>
      <li><a href="{{ url_for('auth.logout') }}">Log Out</a>
    {% else %}
      <li><a href="{{ url_for('auth.register') }}">Register</a>
      <li><a href="{{ url_for('auth.login') }}">Log In</a>
    {% endif %}
  </ul>
</nav>
<section class="content">
  <header>
    {% block header %}{% endblock %}
  </header>
  {% for message in get_flashed_messages() %}
    <div class="flash">{{ message }}</div>
  {% endfor %}
  {% block content %}{% endblock %}
</section>

file_host_app/templates/file_host/index.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Files{% endblock %}</h1>
  {% if g.user %}
    <!--<a class="action" href="{{ url_for('file.upload') }}">New</a>-->
  {% endif %}
{% endblock %}

{% block content %}
  {% for file in files %}
    <article class="file">
      <header>
        <div>
          <h1>{{ file['original_name'] }}</h1>
        </div>
        
      </header>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

file_host_app/templates/file_host/my_files.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}My files{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('file_host.my_files') }}">My files</a>
    <a class="action" href="{{ url_for('file_host.my_links') }}">My links</a>
    <a class="action" href="{{ url_for('file_host.upload') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for file in files %}
    <article class="file">
      <header>
        <div>
          <h1><a class="action" href="{{ url_for('file_host.download', file_id=file['file_id']) }}">{{ file['original_name'] }}</a></h1>
        </div>
        
      </header>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

file_host_app/templates/file_host/my_links.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}My files{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('file_host.my_files') }}">My files</a>
    <a class="action" href="{{ url_for('file_host.my_links') }}">My links</a>
    <a class="action" href="{{ url_for('file_host.upload') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  {% for file in files %}
    <article class="file">
      <header>
        <div>
          <h1><a class="action" href="{{ url_for('file_host.download', file_id=file['file_id']) }}">{{ file['original_name'] }}</a></h1>
        </div>
        
      </header>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

file_host_app/templates/file_host/upload.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New file{% endblock %}</h1>
  {% if g.user %}
    <a class="action" href="{{ url_for('file_host.my_files') }}">My files</a>
    <a class="action" href="{{ url_for('file_host.my_links') }}">My links</a>
    <a class="action" href="{{ url_for('file_host.upload') }}">New</a>
  {% endif %}
{% endblock %}

{% block content %}
  <form method="post" enctype="multipart/form-data">
    <!-- <label for="title">Title</label> -->
    <input type="file" name="file" id="file" value="{{ request.form['file'] }}" required>
    <!-- <label for="body">Body</label> -->
    <!-- <textarea name="body" id="body">{{ request.form['body'] }}</textarea> -->
    <select name="permission" id="permission" value="private">
        <option>private</option>
        <option>pablic</option>
        <option>link</option>
      </select>
    <input type="submit" value="Save">
  </form>
{% endblock %}